### ISSUE TITLE
Dependencies from private repos

### ISSUE THREAD

**Issue by cmgt** [Noooste/akamai-sensor-verifier#1]
Hi friend. Thanks for the interesting project. Can you push the modules that this project links to in the public? Thank you!

```
gitlab.com/azureaio/utils v1.3.1
gitlab.com/azuresolution/akamai v1.6.6
```

**Comment by Noooste** [comment]
Hi, thanks for your report! I will make the changes to fix that bug. But, unfortunately, i won't push these private repos to public.
