### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by klenne** [Noooste/akamai-sensor-verifier#3]
go: downloading github.com/Noooste/fhttp v1.0.7
..\..\..\go\pkg\mod\github.com\!noooste\go-utils@v1.0.0\header.go:4:2: reading github.com/Noooste/fhttp/go.mod at revision v1.0.7: unknown revision v1.0.7

**Comment by Noooste** [comment]
Hi, thanks for reporting it, let me fix it.
